### ISSUE TITLE
Errors when running rails/rake tasks

### ISSUE THREAD

**Issue by ioistired** [Retrospring/retrospring#995]
```
> bundle exec rails i18n:js:export --trace
processing time of bundler require: 1.637s
rails aborted!
Don't know how to build task 'i18n:js:export' (See the list of available tasks with `rails --tasks`)
/home/justask/app/vendor/bundle/ruby/3.1.0/gems/rake-13.0.6/lib/rake/task_manager.rb:59:in `[]'
/home/justask/app/vendor/bundle/ruby/3.1.0/gems/rake-13.0.6/lib/rake/application.rb:159:in `invoke_task'
/home/justask/app/vendor/bundle/ruby/3.1.0/gems/rake-13.0.6/lib/rake/application.rb:116:in `block (2 levels) in top_level'
/home/justask/app/vendor/bundle/ruby/3.1.0/gems/rake-13.0.6/lib/rake/application.rb:116:in `each'
/home/justask/app/vendor/bundle/ruby/3.1.0/gems/rake-13.0.6/lib/rake/application.rb:116:in `block in top_level'
/home/justask/app/vendor/bundle/ruby/3.1.0/gems/rake-13.0.6/lib/rake/application.rb:125:in `run_with_threads'
/home/justask/app/vendor/bundle/ruby/3.1.0/gems/rake-13.0.6/lib/rake/application.rb:110:in `top_level'
/home/justask/app/vendor/bundle/ruby/3.1.0/gems/railties-6.1.7.1/lib/rails/commands/rake/rake_command.rb:24:in `block (2 levels) in perform'
/home/justask/app/vendor/bundle/ruby/3.1.0/gems/rake-13.0.6/lib/rake/application.rb:186:in `standard_exception_handling'
/home/justask/app/vendor/bundle/ruby/3.1.0/gems/railties-6.1.7.1/lib/rails/commands/rake/rake_command.rb:24:in `block in perform'
/home/justask/app/vendor/bundle/ruby/3.1.0/gems/rake-13.0.6/lib/rake/rake_module.rb:59:in `with_application'
/home/justask/app/vendor/bundle/ruby/3.1.0/gems/railties-6.1.7.1/lib/rails/commands/rake/rake_command.rb:18:in `perform'
/home/justask/app/vendor/bundle/ruby/3.1.0/gems/railties-6.1.7.1/lib/rails/command.rb:50:in `invoke'
/home/justask/app/vendor/bundle/ruby/3.1.0/gems/railties-6.1.7.1/lib/rails/commands.rb:18:in `<main>'
/home/justask/app/vendor/bundle/ruby/3.1.0/gems/bootsnap-1.15.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
/home/justask/app/vendor/bundle/ruby/3.1.0/gems/bootsnap-1.15.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
bin/rails:4:in `<main>'
```

```
> bundle exec rails db:migrate --trace
processing time of bundler require: 1.099s
** Invoke db:migrate (first_time)
** Invoke db:load_config (first_time)
** Invoke environment (first_time)
** Execute environment
rails aborted!
NameError: uninitialized constant BetterErrors
/home/justask/app/config/environments/development.rb:78:in `<main>'
/home/justask/app/vendor/bundle/ruby/3.1.0/gems/bootsnap-1.15.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
/home/justask/app/vendor/bundle/ruby/3.1.0/gems/bootsnap-1.15.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
/home/justask/app/vendor/bundle/ruby/3.1.0/gems/zeitwerk-2.6.6/lib/zeitwerk/kernel.rb:38:in `require'
/home/justask/app/vendor/bundle/ruby/3.1.0/gems/railties-6.1.7.1/lib/rails/engine.rb:571:in `block (2 levels) in <class:Engine>'
/home/justask/app/vendor/bundle/ruby/3.1.0/gems/railties-6.1.7.1/lib/rails/engine.rb:570:in `each'
/home/justask/app/vendor/bundle/ruby/3.1.0/gems/railties-6.1.7.1/lib/rails/engine.rb:570:in `block in <class:Engine>'
/home/justask/app/vendor/bundle/ruby/3.1.0/gems/railties-6.1.7.1/lib/rails/initializable.rb:32:in `instance_exec'
/home/justask/app/vendor/bundle/ruby/3.1.0/gems/railties-6.1.7.1/lib/rails/initializable.rb:32:in `run'
/home/justask/app/vendor/bundle/ruby/3.1.0/gems/railties-6.1.7.1/lib/rails/initializable.rb:61:in `block in run_initializers'
/home/justask/.local/share/rbenv/versions/3.1.2/lib/ruby/3.1.0/tsort.rb:228:in `block in tsort_each'
/home/justask/.local/share/rbenv/versions/3.1.2/lib/ruby/3.1.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
/home/justask/.local/share/rbenv/versions/3.1.2/lib/ruby/3.1.0/tsort.rb:422:in `block (2 levels) in each_strongly_connected_component_from'
/home/justask/.local/share/rbenv/versions/3.1.2/lib/ruby/3.1.0/tsort.rb:431:in `each_strongly_connected_component_from'
/home/justask/.local/share/rbenv/versions/3.1.2/lib/ruby/3.1.0/tsort.rb:421:in `block in each_strongly_connected_component_from'
/home/justask/app/vendor/bundle/ruby/3.1.0/gems/railties-6.1.7.1/lib/rails/initializable.rb:50:in `each'
/home/justask/app/vendor/bundle/ruby/3.1.0/gems/railties-6.1.7.1/lib/rails/initializable.rb:50:in `tsort_each_child'
/home/justask/.local/share/rbenv/versions/3.1.2/lib/ruby/3.1.0/tsort.rb:415:in `call'
/home/justask/.local/share/rbenv/versions/3.1.2/lib/ruby/3.1.0/tsort.rb:415:in `each_strongly_connected_component_from'
/home/justask/.local/share/rbenv/versions/3.1.2/lib/ruby/3.1.0/tsort.rb:349:in `block in each_strongly_connected_component'
/home/justask/.local/share/rbenv/versions/3.1.2/lib/ruby/3.1.0/tsort.rb:347:in `each'
/home/justask/.local/share/rbenv/versions/3.1.2/lib/ruby/3.1.0/tsort.rb:347:in `call'
/home/justask/.local/share/rbenv/versions/3.1.2/lib/ruby/3.1.0/tsort.rb:347:in `each_strongly_connected_component'
/home/justask/.local/share/rbenv/versions/3.1.2/lib/ruby/3.1.0/tsort.rb:226:in `tsort_each'
/home/justask/.local/share/rbenv/versions/3.1.2/lib/ruby/3.1.0/tsort.rb:205:in `tsort_each'
/home/justask/app/vendor/bundle/ruby/3.1.0/gems/railties-6.1.7.1/lib/rails/initializable.rb:60:in `run_initializers'
/home/justask/app/vendor/bundle/ruby/3.1.0/gems/railties-6.1.7.1/lib/rails/application.rb:391:in `initialize!'
/home/justask/app/config/environment.rb:6:in `<main>'
/home/justask/app/vendor/bundle/ruby/3.1.0/gems/bootsnap-1.15.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
/home/justask/app/vendor/bundle/ruby/3.1.0/gems/bootsnap-1.15.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
/home/justask/app/vendor/bundle/ruby/3.1.0/gems/zeitwerk-2.6.6/lib/zeitwerk/kernel.rb:38:in `require'
/home/justask/app/vendor/bundle/ruby/3.1.0/gems/railties-6.1.7.1/lib/rails/application.rb:367:in `require_environment!'
/home/justask/app/vendor/bundle/ruby/3.1.0/gems/railties-6.1.7.1/lib/rails/application.rb:533:in `block in run_tasks_blocks'
/home/justask/app/vendor/bundle/ruby/3.1.0/gems/rake-13.0.6/lib/rake/task.rb:281:in `block in execute'
/home/justask/app/vendor/bundle/ruby/3.1.0/gems/rake-13.0.6/lib/rake/task.rb:281:in `each'
/home/justask/app/vendor/bundle/ruby/3.1.0/gems/rake-13.0.6/lib/rake/task.rb:281:in `execute'
/home/justask/app/vendor/bundle/ruby/3.1.0/gems/sentry-ruby-5.7.0/lib/sentry/rake.rb:24:in `execute'
/home/justask/app/vendor/bundle/ruby/3.1.0/gems/rake-13.0.6/lib/rake/task.rb:219:in `block in invoke_with_call_chain'
/home/justask/app/vendor/bundle/ruby/3.1.0/gems/rake-13.0.6/lib/rake/task.rb:199:in `synchronize'
/home/justask/app/vendor/bundle/ruby/3.1.0/gems/rake-13.0.6/lib/rake/task.rb:199:in `invoke_with_call_chain'
/home/justask/app/vendor/bundle/ruby/3.1.0/gems/rake-13.0.6/lib/rake/task.rb:243:in `block in invoke_prerequisites'
/home/justask/app/vendor/bundle/ruby/3.1.0/gems/rake-13.0.6/lib/rake/task.rb:241:in `each'
/home/justask/app/vendor/bundle/ruby/3.1.0/gems/rake-13.0.6/lib/rake/task.rb:241:in `invoke_prerequisites'
/home/justask/app/vendor/bundle/ruby/3.1.0/gems/rake-13.0.6/lib/rake/task.rb:218:in `block in invoke_with_call_chain'
/home/justask/app/vendor/bundle/ruby/3.1.0/gems/rake-13.0.6/lib/rake/task.rb:199:in `synchronize'
/home/justask/app/vendor/bundle/ruby/3.1.0/gems/rake-13.0.6/lib/rake/task.rb:199:in `invoke_with_call_chain'
/home/justask/app/vendor/bundle/ruby/3.1.0/gems/rake-13.0.6/lib/rake/task.rb:243:in `block in invoke_prerequisites'
/home/justask/app/vendor/bundle/ruby/3.1.0/gems/rake-13.0.6/lib/rake/task.rb:241:in `each'
/home/justask/app/vendor/bundle/ruby/3.1.0/gems/rake-13.0.6/lib/rake/task.rb:241:in `invoke_prerequisites'
/home/justask/app/vendor/bundle/ruby/3.1.0/gems/rake-13.0.6/lib/rake/task.rb:218:in `block in invoke_with_call_chain'
/home/justask/app/vendor/bundle/ruby/3.1.0/gems/rake-13.0.6/lib/rake/task.rb:199:in `synchronize'
/home/justask/app/vendor/bundle/ruby/3.1.0/gems/rake-13.0.6/lib/rake/task.rb:199:in `invoke_with_call_chain'
/home/justask/app/vendor/bundle/ruby/3.1.0/gems/rake-13.0.6/lib/rake/task.rb:188:in `invoke'
/home/justask/app/vendor/bundle/ruby/3.1.0/gems/rake-13.0.6/lib/rake/application.rb:160:in `invoke_task'
/home/justask/app/vendor/bundle/ruby/3.1.0/gems/rake-13.0.6/lib/rake/application.rb:116:in `block (2 levels) in top_level'
/home/justask/app/vendor/bundle/ruby/3.1.0/gems/rake-13.0.6/lib/rake/application.rb:116:in `each'
/home/justask/app/vendor/bundle/ruby/3.1.0/gems/rake-13.0.6/lib/rake/application.rb:116:in `block in top_level'
/home/justask/app/vendor/bundle/ruby/3.1.0/gems/rake-13.0.6/lib/rake/application.rb:125:in `run_with_threads'
/home/justask/app/vendor/bundle/ruby/3.1.0/gems/rake-13.0.6/lib/rake/application.rb:110:in `top_level'
/home/justask/app/vendor/bundle/ruby/3.1.0/gems/railties-6.1.7.1/lib/rails/commands/rake/rake_command.rb:24:in `block (2 levels) in perform'
/home/justask/app/vendor/bundle/ruby/3.1.0/gems/rake-13.0.6/lib/rake/application.rb:186:in `standard_exception_handling'
/home/justask/app/vendor/bundle/ruby/3.1.0/gems/railties-6.1.7.1/lib/rails/commands/rake/rake_command.rb:24:in `block in perform'
/home/justask/app/vendor/bundle/ruby/3.1.0/gems/rake-13.0.6/lib/rake/rake_module.rb:59:in `with_application'
/home/justask/app/vendor/bundle/ruby/3.1.0/gems/railties-6.1.7.1/lib/rails/commands/rake/rake_command.rb:18:in `perform'
/home/justask/app/vendor/bundle/ruby/3.1.0/gems/railties-6.1.7.1/lib/rails/command.rb:50:in `invoke'
/home/justask/app/vendor/bundle/ruby/3.1.0/gems/railties-6.1.7.1/lib/rails/commands.rb:18:in `<main>'
/home/justask/app/vendor/bundle/ruby/3.1.0/gems/bootsnap-1.15.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
/home/justask/app/vendor/bundle/ruby/3.1.0/gems/bootsnap-1.15.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
bin/rails:4:in `<main>'
Tasks: TOP => db:migrate => db:load_config => environment
```

I have RAILS_ENV set to `production` in my shell.

**Comment by pixeldesu** [comment]
Oh whoops, looks like we forgot to update the documentation on this one. `i18n.js` switched from Rake tasks to their own CLI in version 4 and the command for locale exporting is `bundle exec i18n export` now.

Also, regarding the second error: I'm not exactly sure why, but it looks like the migration is executed in development context without taking your previously set `RAILS_ENV` into consideration. It should work if you run `bundle exec rails db:migrate RAILS_ENV=production`.

**Comment by ioistired** [comment]
Now I get this:
```
> bundle exec i18n export
=> Config file: "./config/i18n.yml"
=> Require file: "./config/environment.rb"
processing time of bundler require: 1.987s
=> ERROR: couldn't load "./config/environment.rb"

NameError => uninitialized constant BetterErrors
/home/justask/app/config/environments/development.rb:78:in `<main>'
/home/justask/app/vendor/bundle/ruby/3.1.0/gems/bootsnap-1.15.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
/home/justask/app/vendor/bundle/ruby/3.1.0/gems/bootsnap-1.15.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
/home/justask/app/vendor/bundle/ruby/3.1.0/gems/zeitwerk-2.6.6/lib/zeitwerk/kernel.rb:38:in `require'
/home/justask/app/vendor/bundle/ruby/3.1.0/gems/railties-6.1.7.1/lib/rails/engine.rb:571:in `block (2 levels) in <class:Engine>'
/home/justask/app/vendor/bundle/ruby/3.1.0/gems/railties-6.1.7.1/lib/rails/engine.rb:570:in `each'
/home/justask/app/vendor/bundle/ruby/3.1.0/gems/railties-6.1.7.1/lib/rails/engine.rb:570:in `block in <class:Engine>'
/home/justask/app/vendor/bundle/ruby/3.1.0/gems/railties-6.1.7.1/lib/rails/initializable.rb:32:in `instance_exec'
/home/justask/app/vendor/bundle/ruby/3.1.0/gems/railties-6.1.7.1/lib/rails/initializable.rb:32:in `run'
/home/justask/app/vendor/bundle/ruby/3.1.0/gems/railties-6.1.7.1/lib/rails/initializable.rb:61:in `block in run_initializers'
/home/justask/.local/share/rbenv/versions/3.1.2/lib/ruby/3.1.0/tsort.rb:228:in `block in tsort_each'
/home/justask/.local/share/rbenv/versions/3.1.2/lib/ruby/3.1.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
/home/justask/.local/share/rbenv/versions/3.1.2/lib/ruby/3.1.0/tsort.rb:422:in `block (2 levels) in each_strongly_connected_component_from'
/home/justask/.local/share/rbenv/versions/3.1.2/lib/ruby/3.1.0/tsort.rb:431:in `each_strongly_connected_component_from'
/home/justask/.local/share/rbenv/versions/3.1.2/lib/ruby/3.1.0/tsort.rb:421:in `block in each_strongly_connected_component_from'
/home/justask/app/vendor/bundle/ruby/3.1.0/gems/railties-6.1.7.1/lib/rails/initializable.rb:50:in `each'
/home/justask/app/vendor/bundle/ruby/3.1.0/gems/railties-6.1.7.1/lib/rails/initializable.rb:50:in `tsort_each_child'
/home/justask/.local/share/rbenv/versions/3.1.2/lib/ruby/3.1.0/tsort.rb:415:in `call'
/home/justask/.local/share/rbenv/versions/3.1.2/lib/ruby/3.1.0/tsort.rb:415:in `each_strongly_connected_component_from'
/home/justask/.local/share/rbenv/versions/3.1.2/lib/ruby/3.1.0/tsort.rb:349:in `block in each_strongly_connected_component'
/home/justask/.local/share/rbenv/versions/3.1.2/lib/ruby/3.1.0/tsort.rb:347:in `each'
/home/justask/.local/share/rbenv/versions/3.1.2/lib/ruby/3.1.0/tsort.rb:347:in `call'
/home/justask/.local/share/rbenv/versions/3.1.2/lib/ruby/3.1.0/tsort.rb:347:in `each_strongly_connected_component'
/home/justask/.local/share/rbenv/versions/3.1.2/lib/ruby/3.1.0/tsort.rb:226:in `tsort_each'
/home/justask/.local/share/rbenv/versions/3.1.2/lib/ruby/3.1.0/tsort.rb:205:in `tsort_each'
/home/justask/app/vendor/bundle/ruby/3.1.0/gems/railties-6.1.7.1/lib/rails/initializable.rb:60:in `run_initializers'
/home/justask/app/vendor/bundle/ruby/3.1.0/gems/railties-6.1.7.1/lib/rails/application.rb:391:in `initialize!'
/home/justask/app/config/environment.rb:6:in `<top (required)>'
/home/justask/app/vendor/bundle/ruby/3.1.0/gems/i18n-js-4.0.0/lib/i18n-js/cli/command.rb:63:in `load'
/home/justask/app/vendor/bundle/ruby/3.1.0/gems/i18n-js-4.0.0/lib/i18n-js/cli/command.rb:63:in `require_without_warnings'
/home/justask/app/vendor/bundle/ruby/3.1.0/gems/i18n-js-4.0.0/lib/i18n-js/cli/command.rb:43:in `load_require_file!'
/home/justask/app/vendor/bundle/ruby/3.1.0/gems/i18n-js-4.0.0/lib/i18n-js/cli/export_command.rb:65:in `block (2 levels) in <class:ExportCommand>'
/home/justask/.local/share/rbenv/versions/3.1.2/lib/ruby/3.1.0/benchmark.rb:311:in `realtime'
/home/justask/app/vendor/bundle/ruby/3.1.0/gems/i18n-js-4.0.0/lib/i18n-js/cli/export_command.rb:64:in `block in <class:ExportCommand>'
/home/justask/app/vendor/bundle/ruby/3.1.0/gems/i18n-js-4.0.0/lib/i18n-js/cli/command.rb:35:in `call'
/home/justask/app/vendor/bundle/ruby/3.1.0/gems/i18n-js-4.0.0/lib/i18n-js/cli.rb:26:in `call'
/home/justask/app/vendor/bundle/ruby/3.1.0/gems/i18n-js-4.0.0/exe/i18n:5:in `<top (required)>'
/home/justask/app/vendor/bundle/ruby/3.1.0/bin/i18n:25:in `load'
/home/justask/app/vendor/bundle/ruby/3.1.0/bin/i18n:25:in `<top (required)>'
/home/justask/.local/share/rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.3.18/lib/bundler/cli/exec.rb:58:in `load'
/home/justask/.local/share/rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.3.18/lib/bundler/cli/exec.rb:58:in `kernel_load'
/home/justask/.local/share/rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.3.18/lib/bundler/cli/exec.rb:23:in `run'
/home/justask/.local/share/rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.3.18/lib/bundler/cli.rb:483:in `exec'
/home/justask/.local/share/rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.3.18/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/home/justask/.local/share/rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.3.18/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
/home/justask/.local/share/rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.3.18/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
/home/justask/.local/share/rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.3.18/lib/bundler/cli.rb:31:in `dispatch'
/home/justask/.local/share/rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.3.18/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
/home/justask/.local/share/rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.3.18/lib/bundler/cli.rb:25:in `start'
/home/justask/.local/share/rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.3.18/exe/bundle:48:in `block in <top (required)>'
/home/justask/.local/share/rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.3.18/lib/bundler/friendly_errors.rb:120:in `with_friendly_errors'
/home/justask/.local/share/rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.3.18/exe/bundle:36:in `<top (required)>'
/home/justask/.local/share/rbenv/versions/3.1.2/bin/bundle:25:in `load'
/home/justask/.local/share/rbenv/versions/3.1.2/bin/bundle:25:in `<main>'
```

**Comment by nilsding** [comment]
it's still trying to load the development environment, ensure `RAILS_ENV=production` is present in your ENV

**Comment by ioistired** [comment]
Same error

**Comment by ioistired** [comment]
Ah, I thought it was set, but I guess not. Both the i18n and the db migration work now. thank you
